# stateless application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
      - name: springappcontainer
        image: tushar660/spring-boot-mongo:1
        resources:
          requests:
            cpu: 200m
            memory: 266Mi
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
            name: springappconfig
            key: mongodbusername
        - name: MONGO_DB_PASSWORD
          valueFrom:
            configKeyRef:
            name: springappsecret
            key: mongodbpassword
---
#  Kubernetes Service of type NodePort
apiVersion: v1
kind: Service
metadata:
  name: apringappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: springbootapp
  ports:
  - port: 80
    targetPort: 8080
---
# Stateful and ReplicaSet ensures MongoDB Pods are always running
#  with the specified configuration
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: myapp
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodbcontainers
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
            name: springappconfig
            key: mongodbusername
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configKeyRef:
            name: springappsecret
            key: mongodbpassword
        volumeMounts:
        - name: mongodbhostvol
          mountPath: /data/db
      volumes:
      - name: mogodbvol
        PersistentVolumeClaim:
          claimName: mongopvc
---
# This PVC asks the cluster for 1 GiB of storage that can be used by a single pod in the test-ns namespace.
#  If a suitable PersistentVolume (PV) is available  or a StorageClass is set up for dynamic
#  provisioning, the PVC will be bound to it.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
  namespace: test-ns
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
# Kubernetes Service of type ClusterIP to expose a MongoDB application internally within the cluster
apiVersion: v1 
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

