apiVersion: v1
kind: ConfigMap
metadata:
  name: springappconfig
  namespace: test-ns
data:
  mongodbusername: devdb
  
---
apiVersion: v1
kind: Secret
metadata:
  name: springappconfig
  namespace: test-ns
type: Opaque
stringData: # We can define multiple key value pairs.
  mongodbpassword: devdb@123
   