# Deployment configuration for the Java web application
apiVersion: apps/v1  # API version for Deployment resources
kind: Deployment  # Type of resource
metadata:
  name: javawebapp  # Name of the Deployment
spec:
  selector:
    matchLabels:
      app: javawebapp  # Label to identify the pods managed by this Deployment
  template:
    metadata:
      labels:
        app: javawebapp  # Label for the pod template
    spec:
      imagePullSecrets:  # Specifies secrets to pull images from private Docker registries
      - name: <SecretsName>  # Replace with the name of your secret
      containers:
      - name: javawebapp  # Name of the container
        image: <Private Image>  # Docker image to be used (from a private repository)
        resources:  # Resource requests and limits to manage resource allocation
          requests:
            cpu: "200m"  # Minimum CPU required for the container
            memory: "256Mi"  # Minimum memory required for the container
          limits:
            cpu: "300m"  # Maximum CPU allocated for the container
            memory: "500Mi"  # Maximum memory allocated for the container
        ports:
        - containerPort: 8080  # Port exposed by the container
---
# Service configuration to expose the Java web application
apiVersion: v1  # API version for Service resources
kind: Service  # Type of resource
metadata:
  name: myapp  # Name of the Service
spec:
  type: NodePort  # Service type to expose the application on a node's IP and port
  selector:
    app: javawebapp  # Matches the pods with this label
  ports:
  - port: 80  # Port on which the Service is exposed to external clients
    targetPort: 8080  # Port on the pod to which traffic is directed


# Command to create a secret for accessing a private Docker registry
# Replace the placeholders with your actual Docker Hub credentials
# Example:
# kubectl create secret docker-registry tushar660 \
# --docker-server=https://index.docker.io/v1/ \  # Docker registry server URL
# --docker-username=<Your Docker Username> \  # Your Docker Hub username
# --docker-password=<Your Docker Password> \  # Your Docker Hub password
# --docker-email=test@gmail.com -n test-ns  # Email associated with your Docker Hub account and namespace for the secret
