apiVersion: apps/v1
kind: deployment
matadata: 
  name: mavenwebappd
  namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 5 #Revison History
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxSurge: 1
      maxUna vailable: 1
    minReadySeconds: 30
  selector:
  matchLabels:
    app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels: 
        app: mavenwebapp
      spec:
      containes:
      - name: mavenwebappcontainer
        image: tushar660/maven-app:1
        ports: 
        - containesPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /java-web-application/
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /java-web-application/
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
---
# NodePort service 
apiVersion: v1
kind: Service
meradata:
  name: mavenwebappsvc #<serviceName>
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp  #POD labels as selectors                                       
   #  <PODLabelKEY>: <PODLABELVALUE>
  ports:
  - port: 80           #<servicePort>
    targetPort: 8080         #<ContainerPort>
    # NodePort: 30032
---
# HPA For above deployment (mavenwebappd)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mavenwebappdautoscaler
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mavenwebappd
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80


        containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5